### ISSUE TITLE
Required changes for V3 electronics

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/gemctp7user#21]
## Brief summary of issue

Currently `setup_ctp7.sh` can't work with V3 electronics
### Types of issue

- [ ] Bug report (report an issue with the code)
- [x] Feature request (request for change which adds functionality)

## Context (for feature requests)

Following changes are required to adapt the `setup_ctp7.sh` to V3 PROM-less electronics:
- change repositories for the OH and CTP7 FW
- eventually add an option to upgrade a linux image (which is special for the PROM-less design)
    - add the linux image file itself
- accomodate `.pickle` files support. **Note: also might be useful for V2 electronics**
- add RPC modules support (currently user should copy them manually). **Note: also might be useful for V2 electronics**
- add gem loader folder (V3 PROM-less feature)
- fix recover.sh to call cold_boot_tx_invert.sh (V3 only)
- Consider options for downloading the binaries at P5
## Your Environment

* Version used:
* Shell used:

**Comment by bdorney** [comment]
I provide comments on these items below regarding if a separate `v3` vs `v2b` tag is required.

> change repositories for the OH and CTP7 FW

It seems like only the OH repo has changed.  The CTP7 repo is still [GEM_AMC](https://github.com/evka85/GEM_AMC/releases) from @evka85's repo.

Additionally we don't need to change the repo location right, I guess the OH version could be used to determine which directory to point to.  e.g. if `2.X.Y` then the current repo, if `v3.X.Y` then we use `OptohybridV3` repo.

Conclusion: just add a check on the firmware version, does not motivate separate release.

> eventually add an option to upgrade a linux image (which is special for the PROM-less design)

From what I gathered from the [release notes](https://github.com/evka85/GEM_AMC/releases/tag/v3.5.0) of `v3.5.0` upgrading the linux image and then trying to use older versions of the firmware might brick the card:

> IMPORTANT: this release is not compatible with the old linux image, and will crash it instantly when loaded, requiring a power-cycle. Therefore a linux image update is required.

Do we want to have this option? Or at least a check on the CTP7 FW version before the upgrade is performed?  Additionally it seems like only *this* CTP7 FW release has included an update of the linux image.  So how should we handle the case where a future CTP7 FW release is used as a starting point for `setup_ctp7.sh`?  I guess this requires storing the linux image(s) somewhere that is wget-able?  Or we make it always point to the `v3.5.0` link?

Conclusion: Testing with a `v2b` ctp7 should be done to see if there are any issues running the new linux image with the old electronics.  This could be done on `eagle26` in the lab and then we proceed from there (as @evka85 gave us the ability to roll back the image).

> accomodate .pickle files support. Note: also might be useful for V2 electronics

I guess this just needs to add the following lines:

```
rm $XHAL_ROOT/etc/gem_amc_top.pickle
reg_interface.py --execute="kw RELEASE" # this seems to be the easiest way to call `parseXML()` and re-generate a *.pickle file without entering into the `reg_interface.py` tool
cp $XHAL_ROOT/etc/gem_amc_top.pickle xml/
```

Assuming the `xhal` env is set and that the call of `setup_ctp7.sh` happens from with the `gemctp7user` directory (looks like this is already assumed).

Conclusion: does not motivate separate release.

> add RPC modules support (currently user should copy them manually). Note: also might be useful for V2 electronics

Conclusion: Does not motivate separate release.  If anything release control should be done in `ctp7_modules` but presently we have been using `fw_version_check()` within the modules to keep cross-compatibility.

> add gem loader folder (V3 PROM-less feature)

I don't see how this could negatively impact a CTP7 which runs `v2b` setup.

Conclusion: Does not motivate separate release.

> fix recover.sh to call cold_boot_tx_invert.sh (V3 only)

Yeah so this is fundamentally different behavior.  So we should either have different behavior here or a different script `recoverV3.sh` or an option `v2b` or `v3`.

Conclusion: Separate release may not be needed but command line option would be needed.  Default behavior could be assumed to be `v2b` for this year to keep transparent behavior for the GEM DOC team.

> Consider options for downloading the binaries at P5

I think this is a good new feature but doesn't necessitate us freezing a v2b only release.  Additionally in the future we may need to setup a new card in situ at P5.

Conclusion: Does not motivate separate release.

# Summary

Careful consideration required for linux image update procedure is needed.

Command line arguments for `recover.sh` to ensure `v3` vs. `v2b` behavior

**Comment by bdorney** [comment]
I think we can close this right?  Now `setup_ctp7.sh` roughly works for v3 electronics?  Reopen if I'm wrong.
