### ISSUE TITLE
Please add Evaldas

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/gemctp7user#3]
Please add Evaldas as a member of cms-gem-daq-project group so I can assign him as a reviewer. We need him to review the shell scripts (probably some of them are not needed for us).

**Comment by jsturdy** [comment]
I've tried many times... unfortunately ```github``` doesn't allow me to "draft" him :D

**Comment by mexanick** [comment]
Strange... i could do it for the repo i own

On May 24, 2017 21:51, Jared Sturdy <notifications@github.com> wrote:

I've tried many times... unfortunately github doesn't allow me to "draft" him :D
