### ISSUE TITLE
Logging not working after a CTP7 reboot

### ISSUE THREAD

**Issue by lpetre-ulb** [cms-gem-daq-project/gemctp7user#39]
After restarting a CTP7 (with the hot swap tab), the logging service is not restarted.

## Brief summary of issue

Address table corruption requires a reboot of the CTP7. However, after reboot the `syslogd` service is not automatically started and starting it require root access rights. Debugging is made really hard in the absence of error messages in `/var/log/messages`.

``` bash
eagle63:~$ ps -w | grep syslog
 2503 gemuser   2796 S    grep syslog
```

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior

After a CTP7 reboot, the `syslogd` service should be running.

## Current Behavior

After a CTP7 reboot, the `syslogd` service is not started.

``` bash
eagle63:~$ ps -w | grep syslog
 2503 gemuser   2796 S    grep syslog
```

### Steps to Reproduce (for bugs)

1. Power off the CTP7 (with the hot swap tab).
2. Power on the CTP7 (with the hot swap tab).
3. Log in the CTP7, e.g. `ssh gemuser@eagle63`
4. Check if the `syslogd` service is started, e.g. `ps -w | grep syslog`
5. The service is not started.

## Possible Solution (for bugs)

* Automatically start the `syslogd` service after a reboot.
* Create a thin `syslogd` launcher with the `setuid` bit set in order to allow a manual restart (or automatic restart in the `recover.sh` script).

## Your Environment

* CTP7 : eagle63
* CTP7 build ID : CTP7-GENERIC-20180529T153916-0500-4935611
* CTP7 firmware version : 3.7.0
* Shell used : /bin/sh

**Comment by jsturdy** [comment]
@lpetre-ulb, we won't be doing any changes to any scripts, but here are a few things to look at for debugging purposes

* [CTP7] Does `/var/log/messages` exist?
  * If so, what is at the tail end of it and does the last timestamp correspond to any other action?
* [host] Is the `sysmgr` running on the host PC?
  * What is in the `sysmgr` log after rebooting the CTP7?
* Has the CTP7 received the IP configuration for the geographic IP address (non bird name)?
* You can try to power-cycle the CTP7, but before doing this, stop the `sysmgr`
  * This is to isolate a case where the `sysmgr` is stopping the `syslogd` that is started at boot, but fails to restart it with the remote logging option
* [CTP7] What does the output of `/sbin/ifconfig -a` show?
  * Both with and without having the `sysmgr` running on the host PC
* [host] You can try to restart the `sysmgr` and see if this triggers a restart of the `syslogd`
restart the service for remote logging

**Comment by bdorney** [comment]
> @lpetre-ulb, we won't be doing any changes to any scripts, but here are a few things to look at for debugging purposes
> 
>     * [CTP7] Does `/var/log/messages` exist?
>       * If so, what is at the tail end of it and does the last timestamp correspond to any other action?

No it did not exist after power up.

> 
>     * [host] Is the `sysmgr` running on the host PC?
>       * What is in the `sysmgr` log after rebooting the CTP7?

Yes it was running on the PC after boot.  The log file reads:

```
Nov 26 11:53:11 ctp7-pc sysmgr[1783]: C1: Unable to connect to Crate 1: "ipmi_ctx_open_outofband_2_0: rv = -1; errno = 1 (device null)".  Restarting Crate 1 monitoring in 128 seconds.
Nov 26 11:55:39 ctp7-pc sysmgr[1783]: C1: Unable to connect to Crate 1: "ipmi_ctx_open_outofband_2_0: rv = -1; errno = 1 (device null)".  Restarting Crate 1 monitoring in 128 seconds.
```

Not sure where the message at 11:53 comes from; but between 11:53 and 11:55 @lpetre-ulb pulled the hot swap tab here in the lab.

> 
>     * Has the CTP7 received the IP configuration for the geographic IP address (non bird name)?

```bash
OH0: ✓ OH1: ✓ [gemuser@ctp7-pc ~]$ ping gem-shelf01-amc04
ping: gem-shelf01-amc04: Name or service not known
```

No it has not.  When was this addressing implemented?  It's possible I setup this computer before this was added to `machineSetup.sh` in which case it would have to be done manually.  Can you provide instructions here (or point me to the lines in a script where this is done?)?

>     * You can try to power-cycle the CTP7, but before doing this, stop the `sysmgr`
>       * This is to isolate a case where the `sysmgr` is stopping the `syslogd` that is started at boot, but fails to restart it with the remote logging option

We stopped `sysmgr` and rebooted the card and we found that the logging file was not created and `syslogd` was not running.

```bash
eagle63:~$ tail /var/log/messages
tail: can't open '/var/log/messages': No such file or directory
tail: no files
eagle63:~$ ps | grep syslogd
 1199 gemuser   2796 S    grep syslogd
```

>     * [CTP7] What does the output of `/sbin/ifconfig -a` show?
>       * Both with and without having the `sysmgr` running on the host PC

Without `sysmgr` running on the host machine we have:

```bash
eagle63:~$ /sbin/ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:1E:C0:85:72:C9  
          inet addr:192.168.250.71  Bcast:192.168.122.255  Mask:255.255.0.0
          inet6 addr: fe80::21e:c0ff:fe85:72c9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:244 errors:0 dropped:57 overruns:0 frame:0
          TX packets:111 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:19718 (19.2 KiB)  TX bytes:16269 (15.8 KiB)
          Interrupt:147 Base address:0xb000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

After restarting `sysmgr` on the host machine we see no change:

```bash
eagle63:~$ /sbin/ifconfig -a
eth0      Link encap:Ethernet  HWaddr 00:1E:C0:85:72:C9  
          inet addr:192.168.250.71  Bcast:192.168.122.255  Mask:255.255.0.0
          inet6 addr: fe80::21e:c0ff:fe85:72c9/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:384 errors:0 dropped:124 overruns:0 frame:0
          TX packets:120 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:26352 (25.7 KiB)  TX bytes:18335 (17.9 KiB)
          Interrupt:147 Base address:0xb000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

>     * [host] You can try to restart the `sysmgr` and see if this triggers a restart of the `syslogd`

Restarting `sysmgr` on the host machine does *not* trigger a restart of `syslogd`.

>       restart the service for remote logging

Which service is that?

**Comment by jsturdy** [comment]
> Nov 26 11:55:39 ctp7-pc sysmgr[1783]: C1: Unable to connect to Crate 1: "ipmi_ctx_open_outofband_2_0: rv = -1; errno = 1 (device null)".  Restarting Crate 1 monitoring in 128 seconds.

This is probably the underlying issue, the `sysmgr` can't communicate to the MCH over `ipmi`.  I'll try to dig up some debug logs I made in the past when encountering this issue to see what was necessary.
That `syslogd` is not even started at boot is another problem, one that I hope Jes can solve quickly.

> ping: gem-shelf01-amc04: Name or service not known

This specific error is because the `/etc/hosts` file doesn't have the association of name to geographic IP (the geographic IP is set by the `sysmgr` based on `/etc/sysmgr/ipconfig.xml`).  You can modify the `hosts` file to add this association as in 904, but until the geographic IP is sent to the card, connection via this alias, and remote logging, will not be working.

However, the output of your `ifconfig` shows that the geographic IP address has not been assigned.  If it had, you'd have seen a virtual device, e.g., `eth0:0` with the geographic IP (as set from `/etc/sysmgr/ipconfig.xml`)

**Comment by bdorney** [comment]
> This specific error is because the /etc/hosts file doesn't have the association of name to geographic IP (the geographic IP is set by the sysmgr based on /etc/sysmgr/ipconfig.xml)

Okay I'll try to find the time to implement this.

> but until the geographic IP is sent to the card, connection via this alias, and remote logging, will not be working.

Do you mean remote logging by this alias?  Because remote logging as:

```
/var/log/remote/eagle63/messages
```

Works without issue right now (after all subsequent services have been started and are running).

> the output of your ifconfig shows that the geographic IP address has not been assigned.

Got it.

**Comment by lpetre-ulb** [comment]
> > Nov 26 11:55:39 ctp7-pc sysmgr[1783]: C1: Unable to connect to Crate 1: "ipmi_ctx_open_outofband_2_0: rv = -1; errno = 1 (device null)".  Restarting Crate 1 monitoring in 128 seconds.
> 
> This is probably the underlying issue, the `sysmgr` can't communicate to the MCH over `ipmi`. I'll try to dig up some debug logs I made in the past when encountering this issue to see what was necessary.
> That `syslogd` is not even started at boot is another problem, one that I hope Jes can solve quickly.

Could it be related to the MCH exchange we had to perform when the previous MCH stopped working ?

Within `/etc/sysmgr/sysmgr.conf`, the IP address is `192.168.1.240`.

``` bash
crate {
	host = "192.168.1.240"
	mch = "VadaTech"
	username = ""
	password = "vadatech"
        #password = ""
	authtype = none # NONE MD2 MD5 STRAIGHT_PASSWORD_KEY
	description = "GEM Crate"
	log_sel = false
}
```

While the new MCH has no corresponding IP address. 

``` bash
[root@vtipmi root]# ifconfig 
eth0      Link encap:Ethernet  HWaddr 00:13:3A:04:4D:94  
          inet addr:192.168.0.252  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:102178 errors:17 dropped:0 overruns:0 frame:17
          TX packets:26718 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:7765825 (7.4 Mb)  TX bytes:1184310 (1.1 Mb)
          Base address:0xb000 

eth1      Link encap:Ethernet  HWaddr 00:13:3A:04:4D:95  
          inet addr:192.168.40.250  Bcast:192.168.40.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:63765 errors:0 dropped:0 overruns:0 frame:0
          TX packets:101314 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2937236 (2.8 Mb)  TX bytes:5268328 (5.0 Mb)

eth1:1    Link encap:Ethernet  HWaddr 00:13:3A:04:4D:95  
          inet addr:192.168.16.1  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:8    Link encap:Ethernet  HWaddr 00:13:3A:04:4D:95  
          inet addr:192.168.16.33  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:9    Link encap:Ethernet  HWaddr 00:13:3A:04:4D:95  
          inet addr:192.168.16.17  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```
(`192.168.16.17` is the shelf manager IP address)

**Comment by jsturdy** [comment]
> Could it be related to the MCH exchange we had to perform when the previous MCH stopped working ?

I did not know about this, when did this happen, what did the exchange entail (if you can point me to a summary of the intervention)?

 > While the new MCH has no corresponding IP address.

This is probably the root cause

On the one VadaTech MCH we have in 904, I have configured the networks as such:
```bash
[root@vtipmi ~]# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:13:3A:05:1D:84
          inet addr:192.168.1.2  Bcast:192.168.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:49842751 errors:0 dropped:0 overruns:0 frame:0
          TX packets:42178847 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3432281169 (3273.2 Mb)  TX bytes:3174076409 (3027.0 Mb)
          Base address:0xb000

eth1      Link encap:Ethernet  HWaddr 00:13:3A:05:1D:85
          inet addr:192.168.0.2  Bcast:192.168.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:842575 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2864490 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:38834269 (37.0 Mb)  TX bytes:148953480 (142.0 Mb)

eth1:1    Link encap:Ethernet  HWaddr 00:13:3A:05:1D:85
          inet addr:192.168.16.1  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:8    Link encap:Ethernet  HWaddr 00:13:3A:05:1D:85
          inet addr:192.168.16.33  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

eth1:9    Link encap:Ethernet  HWaddr 00:13:3A:05:1D:85
          inet addr:192.168.16.17  Bcast:192.168.16.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:16436  Metric:1
          RX packets:140900908 errors:0 dropped:0 overruns:0 frame:0
          TX packets:140900908 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:3352461726 (3197.1 Mb)  TX bytes:3352461726 (3197.1 Mb)
```
and the `sysmgr` is configured to connect over `ipmi` to `192.168.1.2`

You should update the `sysmgr.conf` file to use one of the primary connections (`eth0/1`) and then restart `sysmgr`

**Comment by lpetre-ulb** [comment]
> > Could it be related to the MCH exchange we had to perform when the previous MCH stopped working ?
> 
> I did not know about this, when did this happen, what did the exchange entail (if you can point me to a summary of the intervention)?

The only information I can find is an email exchange you had with Gilles and Brian : "MCH issue in ULB set-up" during end of August 2018. You were not included in the last email in which the relevant extract is :

On 22/08/2018 16:45, Gilles De Lentdecker wrote:
```
I have exchanged the MCH of my crate with the one from my colleague.
The new MCH (also Vadatech) seems to power on correctly in our ULB set-up so we can resume using the ULB v3 setup.
```

I was not present at that time so I do not know more.

> > While the new MCH has no corresponding IP address.
> 
> This is probably the root cause
> 
> On the one VadaTech MCH we have in 904, I have configured the networks as such:
> [...]
> and the `sysmgr` is configured to connect over `ipmi` to `192.168.1.2`
> 
> You should update the `sysmgr.conf` file to use one of the primary connections (`eth0/1`) and then restart `sysmgr`

Thank you very much. I'll either update `sysmgr.conf` or maybe configure the MCH IP address (since we should receive a new one at ULB soon and I have access rights to the MCH but not to the DAQ machine).

**Comment by jsturdy** [comment]
OK, I guess I'm surprised `sysmgr` related issues weren't noticed when the exchange was made initially... (it's not relevant for all operational modes, so maybe that's why)

Unless you have a mechanism set up to assign the IP addresses over the network in some programattic way, I'd suggest labeling each MCH, and then giving each one a unique set of IP addresses (unless you don't expect multiples of them to be simultaneously in use in the same local network, in which case, you can probably keep all of them identical, and then avoid problems with a hot swap)

**Comment by lpetre-ulb** [comment]
> Unless you have a mechanism set up to assign the IP addresses over the network in some programattic way, I'd suggest labeling each MCH, and then giving each one a unique set of IP addresses (unless you don't expect multiples of them to be simultaneously in use in the same local network, in which case, you can probably keep all of them identical, and then avoid problems with a hot swap)

Ah, yes, labeling the MCH's is a good idea, thanks ! Altough, there will normally be only one MCH in the same local network at ULB.

**Comment by lpetre-ulb** [comment]
The logging was not working only due to an improper configuration of the `sysmgr` daemon.
