### ISSUE TITLE
restart_ipbus.sh incorrectly reports that ipbus already running

### ISSUE THREAD

**Issue by AndrewLevin** [cms-gem-daq-project/gemctp7user#45]
`restart_ipbus.sh` does not restart ipbus

## Brief summary of issue
When ` restart_ipbus.sh` is run and `ipbus` is not running, it incorrectly reports that `ipbus` is running, and does not restart it. `ipbus` can be restarted manually 

```
NOW=$(date +"%H-%M-%m-%d-%Y")
nohup ipbus 2>&1 > ${HOME}/logs/ipbus_${NOW}.log
```

but it would be good if the script were fixed.

### Types of issue

- [x] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Current Behavior

Running ` restart_ipbus.sh` does not actually restart ipbus, as shown below.

```
eagle34:~$ which  restart_ipbus.sh
/mnt/persistent/gemdaq/scripts/restart_ipbus.sh
eagle34:~$ cat `which  restart_ipbus.sh`
#!/bin/sh

ipbstatus=$(ps |grep [i]pbus)

if [ "$?" = "1" ]
then
    NOW=$(date +"%H-%M-%m-%d-%Y")
    echo "nohup ipbus 2>&1 > ${HOME}/logs/ipbus_${NOW}.log"
    nohup ipbus 2>&1 > ${HOME}/logs/ipbus_${NOW}.log
else
    echo "ipbus is running, not restarting"
fi
eagle34:~$ ps | grep ipbus
 3048 gemuser   2796 S    grep ipbus
eagle34:~$ restart_ipbus.sh
ipbus is running, not restarting
eagle34:~$ ps | grep ipbus                    
 3066 gemuser   2796 S    grep ipbus
```

### Steps to Reproduce (for bugs)
1. This problem was found on `eagle34`

## Your Environment

* Version used:
* Shell used:

**Comment by jsturdy** [comment]
One thing that was tested by @AndrewLevin was that for the user he was using to test, the `$HOME/logs` directory did not exist.
This *could* cause the restart step to fail, however, it would not cause the previous check to fail.
To remedy this, a check on the existence of `$HOME/logs` should be added, and if missing, the directory should be created.

**Comment by mexanick** [comment]
on top of this, even when then logs directory is present, the check on whether the `ipbus` is running still fails, so the main issue persists

**Comment by jsturdy** [comment]
When I cycled the image on `eagle34` today, the recover script did not encounter any issues (other than the expected `gemuser` being unable to kill the `rpcsvc` owned by `texas`).
A manual check now produces the expected behaviour of no action as the `ipbus` service is running.
After killing, it also restarts the service as expected.

**Comment by AndrewLevin** [comment]
That is interesting, can you show the terminal output?

**Comment by jsturdy** [comment]
```
eagle34:~$ whoami
gemuser
eagle34:~$ restart_ipbus.sh
ipbus is running, not restarting
2471 gemuser 3452 S ipbus
eagle34:~$ killall ipbus
eagle34:~$ echo $?
0
eagle34:~$ ps|egrep '[r]pc|[i]pb'
  384 root         0 SW<  [rpciod]
 2476 gemuser   4040 S    rpcsvc
 2560 gemuser   266m S    rpcsvc
eagle34:~$ restart_ipbus.sh
nohup ipbus 2>&1 > /mnt/persistent/gemuser/logs/ipbus_13-21-03-13-2019.log
```

**Comment by AndrewLevin** [comment]
ok, likely this is because you are using the `v2` version of the script and I was using the `v3` version of the script:

```
eagle34:~$ diff /mnt/persistent/gemdaq_v2/scripts/restart_ipbus.sh  /mnt/persistent/gemdaq_v3/scripts/restart_ipbus.sh
--- /mnt/persistent/gemdaq_v2/scripts/restart_ipbus.sh
+++ /mnt/persistent/gemdaq_v3/scripts/restart_ipbus.sh
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-ipbstatus=$(ps | grep [i]pbus|egrep -v restart)
+ipbstatus=$(ps |grep [i]pbus)
 
 if [ "$?" = "1" ]
 then
@@ -9,5 +9,4 @@
     nohup ipbus 2>&1 > ${HOME}/logs/ipbus_${NOW}.log
 else
     echo "ipbus is running, not restarting"
-    echo $ipbstatus
 fi
eagle34:~$ 
```

**Comment by jsturdy** [comment]
Ah, yes, that does look like something I may have tweaked in the past, the extra exclusion searches only for the `ipbus` service, not the restart.
I've modified both scripts on `eagle34` to now instead simply do:
```sh
ipbstatus=$(ps | egrep 'ipbus$')
```
to only search for the `ipbus` service.
This can be patched into the script in this repository

**Comment by bdorney** [comment]
> This ~~can~~ **should** be patched into the script in this repository

FTFY

**Comment by mexanick** [comment]
This issue is still present and is very annoying
