### ISSUE TITLE
Configuration parameters for hardware

### ISSUE THREAD

**Issue by mexanick** [cms-gem-daq-project/gemctp7user#7]
Should we add some structure for the HW parameters (e.g. VFAT throsholds/latencies/trims etc...)?

**Comment by cbravo135** [comment]
I think we discussed this once. The approach which I liked the most was to build a text file
that could be loaded the the CTP7 with all of the parameters which could be written to the
detectors via an RPC. Eventually the configuration manager would read the database and
write the file to the CTP7 with a load command. Then a write command would initiate the RPC.

**Comment by mexanick** [comment]
Correct. I'm wondering if we should foresee a folder structure for these text files _here,_ or you guys have _other_ locations in mind.

**Comment by cbravo135** [comment]
I think this makes sense to do here. We should get Jared's opinion too, but it seems logical to me.

**Comment by mexanick** [comment]
Closing as outdated
